version: '3.8'

services: 
  dev: 
    container_name: nestjs_docker_container_dev
    image: nestjs_docker_image_dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports: 
      - 3000:3000
      - 9229:9229
    networks:
      - jbadilla-docker-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  
  prod:
    container_name: nestjs_docker_container_prod
    image: nestjs_docker_image_prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports: 
      - 3000:3000
      - 9229:9229
    networks:
      - jbadilla-docker-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  jbadilla-docker-network: